name: guillermo-demo-devops-nodejs
services:
  node:
    container_name: guillermo-node-app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8080:8000
    restart: always
