name: workflow-demo-devops-nodejs
on:
  push:
    branches:
    - master

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:

    - name: checkout
      uses: actions/checkout@v4.1.0

    - name: Install Node.js
      uses: actions/setup-node@v4.0.0
      with:
        node-version: 18.x

    - name: Code Build
      run: npm i

    - name: Unit Tests
      run: npm run test

    - name: Static Code analysis
      uses: codacy/codacy-analysis-cli-action@master
      with:
        verbose: false

    - name: Code Coverage
      run: npx jest --coverage

    - name: Code Coverage analysis
      id: code-coverage
      uses: barecheck/code-coverage-action@v1
      with:
        barecheck-github-app-token: ${{ secrets.BARECHECK_GITHUB_APP_TOKEN  }}
        lcov-file: "./coverage/lcov.info"
        base-lcov-file: "./lcov-base.info"
        send-summary-comment: true
        show-annotations: "warning"

  Build_Docker_Image:
    needs:
    - CI

    runs-on: ubuntu-latest

    steps:

    - name: checkout
      uses: actions/checkout@v4.1.0

    - name: BuildAndPush
      uses: docker/login-action@v3.3.0
      with:
        username: "${{ secrets.DOCKERHUBCONNECTION_DOCKER_USERNAME }}"
        password: "${{ secrets.DOCKERHUBCONNECTION_DOCKER_PASSWORD }}"

    - name: Build the Docker image
      run: docker build . --file "Dockerfile" -t ahioros/demo-devops-nodejs:${{ github.run_id }}

    - name: Create latest tag image as well
      run: docker tag ahioros/demo-devops-nodejs:${{ github.run_id }} ahioros/demo-devops-nodejs:latest

    - name: Push Docker image with the version number
      run: docker push ahioros/demo-devops-nodejs:${{ github.run_id }}

    - name: Push the latest tag
      run: docker push ahioros/demo-devops-nodejs:latest

    - name: Logout
      run: docker logout

    - name: Scan for vulnerabilities
      uses: crazy-max/ghaction-container-scan@v3
      with:
        image: ahioros/demo-devops-nodejs:latest
      env:
        TRIVY_TIMEOUT: 3m

  Deployment:
    needs:
    - Build_Docker_Image

    runs-on: ubuntu-latest
    steps:

    - name: checkout
      uses: actions/checkout@v4.1.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: ahioros/Deploy-Demo-devops-nodejs
        fetch-depth: 0
        persist-credentials: false

    - name: Deploy
      run: |-
        TAG=${{ github.run_id }}
        EXP="image: ahioros/demo-devops-nodejs:[0-9]+"
        REP="image: ahioros/demo-devops-nodejs:$TAG"
        sed -E -i "s|$EXP|$REP|g" k8s/05-deployment.yaml
        git config user.name  "Argo CD"
        git config user.email "ArgoCD@example.com"
        git checkout master --
        git add --all
        git commit -m "Deployment ID: ${{ github.run_id }}"
      shell: bash

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        repository: ahioros/Deploy-Demo-devops-nodejs
        GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
